# .github/workflows/docs.yml

name: 'Docs: Build and Deploy'

on:
    # Trigger the workflow on pushes to the main branch
    push:
        branches:
            - main

# Allow this job to clone the repo and create a page deployment
permissions:
    contents: read
    pages: write
    id-token: write

jobs:
    build-and-deploy:
        runs-on: ubuntu-slim
        steps:
            - name: 'Checkout ğŸ›ï¸'
              uses: actions/checkout@v4

            - name: 'Setup Node.js âš™ï¸'
              uses: actions/setup-node@v4
              with:
                  node-version: '24' # using LTS (even numbered) version
                  cache: 'npm'

            - name: 'Install Dependencies ğŸ“¦'
              # Using npm ci for faster, more reliable installs in CI
              run: npm ci

            - name: 'Build all packages ğŸš€'
              # This script uses lerna (using nx & tsup) to build all packages
              run: npm run build

            - name: 'Build VitePress Site ğŸš€'
              # This script runs 'typedoc' and then 'vitepress build'
              run: npm run docs:build

            - name: 'Upload artifact ğŸ“¦'
              uses: actions/upload-pages-artifact@v3
              with:
                  # This is the default output directory for VitePress
                  path: docs/.vitepress/dist

            - name: 'Deploy to GitHub Pages ğŸš€'
              id: deployment
              uses: actions/deploy-pages@v4
